- name: install apache2 
  remote_user: azureuser
  hosts: 20.107.178.151
  become: true 
  become_user: root 
  gather_facts: true 
  tasks: 
    - name: "Install apache2" 
      package: 
        name=apache2 
        state=present
